### PR TITLE
Wei update

### PR DESCRIPTION
**Pull request by Wei1150**

### CODE REVIEW

**Review by joycechen612 — COMMENTED** [review]
This is not util function, everyOne use this method will loading to the demo.com website.But what if I want to go the different website ?

**Review by ShaolingStouder — DISMISSED** [review]
LGTM!

**Review by WenjiZ — COMMENTED** [review]
driver.get("website"), website doesn't need double quotes.

**Review by WenjiZ — APPROVED** [review]
LGTM!

**Review by joycechen612 — APPROVED** [review]
Looks Good

**Review by ShaolingStouder — APPROVED** [review]
LGTM!

**Review by boratech-macmini — APPROVED** [review]

**Pull request merged**
